-- MySQL Script generated by MySQL Workbench
-- Sat Jul 30 23:25:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sai
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sai` ;

-- -----------------------------------------------------
-- Schema sai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sai` DEFAULT CHARACTER SET utf8mb4 ;
USE `sai` ;

-- -----------------------------------------------------
-- Table `sai`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`family` ;

CREATE TABLE IF NOT EXISTS `sai`.`family` (
  `family_id` VARCHAR(10) NOT NULL,
  `family_name` VARCHAR(20) NULL,
  `family_image_path` VARCHAR(255) NULL,
  `family_image_name` VARCHAR(255) NULL,
  `family_image_type` VARCHAR(10) NULL,
  PRIMARY KEY (`family_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`album` ;

CREATE TABLE IF NOT EXISTS `sai`.`album` (
  `album_id` BIGINT NOT NULL AUTO_INCREMENT,
  `family_id` VARCHAR(10) NOT NULL,
  `album_name` VARCHAR(30) NOT NULL,
  `album_start_date` DATE NULL,
  `album_end_date` DATE NULL,
  PRIMARY KEY (`album_id`),
  INDEX `FK_FAMILY_TO_ALBUM_1` (`family_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_ALBUM_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`user` ;

CREATE TABLE IF NOT EXISTS `sai`.`user` (
  `user_id` VARCHAR(20) NOT NULL,
  `family_id` VARCHAR(10) NULL,
  `user_name` VARCHAR(10) NULL,
  `email` VARCHAR(30) NULL,
  `password` VARCHAR(20) NULL,
  `user_type` VARCHAR(30) NULL,
  `birthday` DATE NULL,
  `lunar` TINYINT(1) NULL,
  `user_image_path` VARCHAR(255) NULL,
  `user_image_name` VARCHAR(255) NULL,
  `user_image_type` VARCHAR(10) NULL,
  `user_message` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FK_FAMILY_TO_USER_1` (`family_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_USER_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`board` ;

CREATE TABLE IF NOT EXISTS `sai`.`board` (
  `board_id` BIGINT NOT NULL AUTO_INCREMENT,
  `family_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `board_content` VARCHAR(1000) NULL,
  `board_reg_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `board_media_yn` TINYINT(1) NULL,
  `poll_yn` TINYINT(1) NULL,
  `board_date` DATE NULL,
  `board_location` VARCHAR(40) NULL,
  `board_people_yn` TINYINT(1) NULL,
  PRIMARY KEY (`board_id`),
  INDEX `FK_FAMILY_TO_BOARD_1` (`family_id` ASC) VISIBLE,
  INDEX `FK_USER_TO_BOARD_1` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_BOARD_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_TO_BOARD_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`board_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`board_media` ;

CREATE TABLE IF NOT EXISTS `sai`.`board_media` (
  `board_meida_id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `board_media_path` VARCHAR(255) NOT NULL,
  `board_media_name` VARCHAR(255) NOT NULL,
  `board_media_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`board_meida_id`),
  INDEX `FK_BOARD_TO_BOARD_MEDIA_1` (`board_id` ASC) VISIBLE,
  CONSTRAINT `FK_BOARD_TO_BOARD_MEDIA_1`
    FOREIGN KEY (`board_id`)
    REFERENCES `sai`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`board_tagged`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`board_tagged` ;

CREATE TABLE IF NOT EXISTS `sai`.`board_tagged` (
  `board_tagged_id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`board_tagged_id`),
  INDEX `FK_BOARD_TO_BOARD_TAGGED_1` (`board_id` ASC) VISIBLE,
  INDEX `fk_board_tagged_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_BOARD_TO_BOARD_TAGGED_1`
    FOREIGN KEY (`board_id`)
    REFERENCES `sai`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_board_tagged_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`family_callsign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`family_callsign` ;

CREATE TABLE IF NOT EXISTS `sai`.`family_callsign` (
  `family_callsign_id` BIGINT NOT NULL AUTO_INCREMENT,
  `from_user_id` VARCHAR(20) NOT NULL,
  `to_user_id` VARCHAR(20) NOT NULL,
  `callsign` VARCHAR(30) NULL,
  PRIMARY KEY (`family_callsign_id`),
  INDEX `fk_family_callsign_user1_idx` (`from_user_id` ASC) VISIBLE,
  INDEX `fk_family_callsign_user2_idx` (`to_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_family_callsign_user1`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_family_callsign_user2`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`family_register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`family_register` ;

CREATE TABLE IF NOT EXISTS `sai`.`family_register` (
  `family_register_id` BIGINT NOT NULL AUTO_INCREMENT,
  `family_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `approve_yn` TINYINT(1) NULL,
  PRIMARY KEY (`family_register_id`),
  INDEX `FK_FAMILY_TO_FAMILY_REGISTER_1` (`family_id` ASC) VISIBLE,
  INDEX `FK_USER_TO_FAMILY_REGISTER_1` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_FAMILY_REGISTER_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_TO_FAMILY_REGISTER_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`main_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`main_plan` ;

CREATE TABLE IF NOT EXISTS `sai`.`main_plan` (
  `main_plan_id` BIGINT NOT NULL AUTO_INCREMENT,
  `family_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(20) NULL,
  `plan_type` VARCHAR(10) NULL,
  `plan_title` VARCHAR(100) NOT NULL,
  `main_plan_start_datetime` DATETIME NULL,
  `main_plan_end_datetime` DATETIME NULL,
  `plan_noti_datetime` INT NULL,
  `plan_routine_day` INT NULL,
  `routine_end_date` DATE NULL,
  PRIMARY KEY (`main_plan_id`),
  INDEX `FK_FAMILY_TO_MASTER_PLAN_1` (`family_id` ASC) VISIBLE,
  INDEX `FK_USER_TO_MASTER_PLAN_1` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_MASTER_PLAN_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_TO_MASTER_PLAN_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`album_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`album_media` ;

CREATE TABLE IF NOT EXISTS `sai`.`album_media` (
  `album_media_id` BIGINT NOT NULL AUTO_INCREMENT,
  `album_id` BIGINT NOT NULL,
  `album_media_path` VARCHAR(255) NULL,
  `album_media_name` VARCHAR(255) NULL,
  `album_media_type` VARCHAR(10) NULL,
  PRIMARY KEY (`album_media_id`),
  INDEX `FK_ALBUM_TO_MEDIA_1` (`album_id` ASC) VISIBLE,
  CONSTRAINT `FK_ALBUM_TO_MEDIA_1`
    FOREIGN KEY (`album_id`)
    REFERENCES `sai`.`album` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`memo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`memo` ;

CREATE TABLE IF NOT EXISTS `sai`.`memo` (
  `memo_id` BIGINT NOT NULL AUTO_INCREMENT,
  `family_id` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(20) NULL,
  `memo_reg_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `color` VARCHAR(10) NULL,
  `memo_content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`memo_id`),
  INDEX `FK_USER_TO_MEMO_1` (`user_id` ASC) VISIBLE,
  INDEX `FK_FAMILY_TO_MEMO_1` (`family_id` ASC) VISIBLE,
  CONSTRAINT `FK_FAMILY_TO_MEMO_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `sai`.`family` (`family_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_TO_MEMO_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`notification` ;

CREATE TABLE IF NOT EXISTS `sai`.`notification` (
  `noti_id` BIGINT NOT NULL AUTO_INCREMENT,
  `noti_to_user_id` VARCHAR(20) NOT NULL,
  `noti_from_user_id` VARCHAR(20) NULL,
  `noti_content` VARCHAR(255) NULL,
  `noti_type` VARCHAR(20) NULL,
  `noti_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `noti_read_yn` TINYINT(1) NULL,
  `noti_content_id` BIGINT NULL,
  PRIMARY KEY (`noti_id`),
  INDEX `FK_USER_TO_Notification_1` (`noti_to_user_id` ASC) VISIBLE,
  INDEX `fk_notification_user1_idx` (`noti_from_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_USER_TO_Notification_1`
    FOREIGN KEY (`noti_to_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`noti_from_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`plan_tagged`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`plan_tagged` ;

CREATE TABLE IF NOT EXISTS `sai`.`plan_tagged` (
  `plan_tagged_id` BIGINT NOT NULL AUTO_INCREMENT,
  `plan_id` BIGINT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`plan_tagged_id`),
  INDEX `FK_MASTER_PLAN_TO_PLAN_TAGGED_1` (`plan_id` ASC) VISIBLE,
  INDEX `FK_USER_TO_PLAN_TAGGED_1` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_MASTER_PLAN_TO_PLAN_TAGGED_1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `sai`.`main_plan` (`main_plan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_TO_PLAN_TAGGED_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`poll` ;

CREATE TABLE IF NOT EXISTS `sai`.`poll` (
  `poll_id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `poll_title` VARCHAR(40) NOT NULL,
  `poll_option1` VARCHAR(100) NOT NULL,
  `poll_option2` VARCHAR(100) NOT NULL,
  `poll_option3` VARCHAR(100) NULL,
  `poll_option4` VARCHAR(100) NULL,
  `poll_option5` VARCHAR(100) NULL,
  `poll_end_datetime` DATETIME NULL,
  PRIMARY KEY (`poll_id`),
  INDEX `FK_BOARD_TO_POLL_1` (`board_id` ASC) VISIBLE,
  CONSTRAINT `FK_BOARD_TO_POLL_1`
    FOREIGN KEY (`board_id`)
    REFERENCES `sai`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`poll_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`poll_result` ;

CREATE TABLE IF NOT EXISTS `sai`.`poll_result` (
  `poll_result_id` BIGINT NOT NULL AUTO_INCREMENT,
  `poll_id` BIGINT NOT NULL,
  `poll_result_user_id` VARCHAR(20) NOT NULL,
  `poll_result` VARCHAR(20) NOT NULL,
  INDEX `FK_POLL_TO_POLL_RESULT_1` (`poll_id` ASC) VISIBLE,
  PRIMARY KEY (`poll_result_id`),
  INDEX `fk_poll_result_user1_idx` (`poll_result_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_POLL_TO_POLL_RESULT_1`
    FOREIGN KEY (`poll_id`)
    REFERENCES `sai`.`poll` (`poll_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_poll_result_user1`
    FOREIGN KEY (`poll_result_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`reaction` ;

CREATE TABLE IF NOT EXISTS `sai`.`reaction` (
  `reaction_id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `reaction_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`reaction_id`),
  INDEX `FK_BOARD_TO_REACTION_1` (`board_id` ASC) VISIBLE,
  CONSTRAINT `FK_BOARD_TO_REACTION_1`
    FOREIGN KEY (`board_id`)
    REFERENCES `sai`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`reply` ;

CREATE TABLE IF NOT EXISTS `sai`.`reply` (
  `reply_id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `reply_user_id` VARCHAR(20) NOT NULL,
  `reply_content` VARCHAR(200) NOT NULL,
  `reply_reg_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reply_id`),
  INDEX `FK_BOARD_TO_REPLY_1` (`board_id` ASC) VISIBLE,
  INDEX `fk_reply_user1_idx` (`reply_user_id` ASC) VISIBLE,
  CONSTRAINT `FK_BOARD_TO_REPLY_1`
    FOREIGN KEY (`board_id`)
    REFERENCES `sai`.`board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reply_user1`
    FOREIGN KEY (`reply_user_id`)
    REFERENCES `sai`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sai`.`sub_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sai`.`sub_plan` ;

CREATE TABLE IF NOT EXISTS `sai`.`sub_plan` (
  `sub_plan_id` BIGINT NOT NULL AUTO_INCREMENT,
  `main_plan_id` BIGINT NOT NULL,
  `sub_plan_start_datetime` DATETIME NULL,
  `sub_plan_end_datetime` DATETIME NULL,
  PRIMARY KEY (`sub_plan_id`),
  INDEX `FK_MASTER_PLAN_TO_SLAVE_PLAN_1` (`main_plan_id` ASC) VISIBLE,
  CONSTRAINT `FK_MASTER_PLAN_TO_SLAVE_PLAN_1`
    FOREIGN KEY (`main_plan_id`)
    REFERENCES `sai`.`main_plan` (`main_plan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
